// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simple.proto

package ru.spbu.pt.bd.grpc;

/**
 * Protobuf type {@code FactorResponse}
 */
public  final class FactorResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FactorResponse)
    FactorResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FactorResponse.newBuilder() to construct.
  private FactorResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FactorResponse() {
    formattedFactorized_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FactorResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            formattedFactorized_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.spbu.pt.bd.grpc.SampleServiceProto.internal_static_FactorResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.spbu.pt.bd.grpc.SampleServiceProto.internal_static_FactorResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.spbu.pt.bd.grpc.FactorResponse.class, ru.spbu.pt.bd.grpc.FactorResponse.Builder.class);
  }

  public static final int FORMATTEDFACTORIZED_FIELD_NUMBER = 1;
  private volatile java.lang.Object formattedFactorized_;
  /**
   * <code>string formattedFactorized = 1;</code>
   */
  public java.lang.String getFormattedFactorized() {
    java.lang.Object ref = formattedFactorized_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      formattedFactorized_ = s;
      return s;
    }
  }
  /**
   * <code>string formattedFactorized = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFormattedFactorizedBytes() {
    java.lang.Object ref = formattedFactorized_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      formattedFactorized_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFormattedFactorizedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, formattedFactorized_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFormattedFactorizedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, formattedFactorized_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.spbu.pt.bd.grpc.FactorResponse)) {
      return super.equals(obj);
    }
    ru.spbu.pt.bd.grpc.FactorResponse other = (ru.spbu.pt.bd.grpc.FactorResponse) obj;

    boolean result = true;
    result = result && getFormattedFactorized()
        .equals(other.getFormattedFactorized());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FORMATTEDFACTORIZED_FIELD_NUMBER;
    hash = (53 * hash) + getFormattedFactorized().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.spbu.pt.bd.grpc.FactorResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.spbu.pt.bd.grpc.FactorResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.spbu.pt.bd.grpc.FactorResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.spbu.pt.bd.grpc.FactorResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.spbu.pt.bd.grpc.FactorResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.spbu.pt.bd.grpc.FactorResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.spbu.pt.bd.grpc.FactorResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.spbu.pt.bd.grpc.FactorResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.spbu.pt.bd.grpc.FactorResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.spbu.pt.bd.grpc.FactorResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.spbu.pt.bd.grpc.FactorResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.spbu.pt.bd.grpc.FactorResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.spbu.pt.bd.grpc.FactorResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code FactorResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FactorResponse)
      ru.spbu.pt.bd.grpc.FactorResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.spbu.pt.bd.grpc.SampleServiceProto.internal_static_FactorResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.spbu.pt.bd.grpc.SampleServiceProto.internal_static_FactorResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.spbu.pt.bd.grpc.FactorResponse.class, ru.spbu.pt.bd.grpc.FactorResponse.Builder.class);
    }

    // Construct using ru.spbu.pt.bd.grpc.FactorResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      formattedFactorized_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.spbu.pt.bd.grpc.SampleServiceProto.internal_static_FactorResponse_descriptor;
    }

    public ru.spbu.pt.bd.grpc.FactorResponse getDefaultInstanceForType() {
      return ru.spbu.pt.bd.grpc.FactorResponse.getDefaultInstance();
    }

    public ru.spbu.pt.bd.grpc.FactorResponse build() {
      ru.spbu.pt.bd.grpc.FactorResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ru.spbu.pt.bd.grpc.FactorResponse buildPartial() {
      ru.spbu.pt.bd.grpc.FactorResponse result = new ru.spbu.pt.bd.grpc.FactorResponse(this);
      result.formattedFactorized_ = formattedFactorized_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.spbu.pt.bd.grpc.FactorResponse) {
        return mergeFrom((ru.spbu.pt.bd.grpc.FactorResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.spbu.pt.bd.grpc.FactorResponse other) {
      if (other == ru.spbu.pt.bd.grpc.FactorResponse.getDefaultInstance()) return this;
      if (!other.getFormattedFactorized().isEmpty()) {
        formattedFactorized_ = other.formattedFactorized_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ru.spbu.pt.bd.grpc.FactorResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ru.spbu.pt.bd.grpc.FactorResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object formattedFactorized_ = "";
    /**
     * <code>string formattedFactorized = 1;</code>
     */
    public java.lang.String getFormattedFactorized() {
      java.lang.Object ref = formattedFactorized_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        formattedFactorized_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string formattedFactorized = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFormattedFactorizedBytes() {
      java.lang.Object ref = formattedFactorized_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        formattedFactorized_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string formattedFactorized = 1;</code>
     */
    public Builder setFormattedFactorized(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      formattedFactorized_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string formattedFactorized = 1;</code>
     */
    public Builder clearFormattedFactorized() {
      
      formattedFactorized_ = getDefaultInstance().getFormattedFactorized();
      onChanged();
      return this;
    }
    /**
     * <code>string formattedFactorized = 1;</code>
     */
    public Builder setFormattedFactorizedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      formattedFactorized_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:FactorResponse)
  }

  // @@protoc_insertion_point(class_scope:FactorResponse)
  private static final ru.spbu.pt.bd.grpc.FactorResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.spbu.pt.bd.grpc.FactorResponse();
  }

  public static ru.spbu.pt.bd.grpc.FactorResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FactorResponse>
      PARSER = new com.google.protobuf.AbstractParser<FactorResponse>() {
    public FactorResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new FactorResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FactorResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FactorResponse> getParserForType() {
    return PARSER;
  }

  public ru.spbu.pt.bd.grpc.FactorResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

