// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simple.proto

package ru.spbu.pt.bd.grpc;

public interface FactorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FactorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 number = 1;</code>
   */
  long getNumber();
}
