// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simple.proto

package ru.spbu.pt.bd.grpc;

public interface FactorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FactorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string formattedFactorized = 1;</code>
   */
  java.lang.String getFormattedFactorized();
  /**
   * <code>string formattedFactorized = 1;</code>
   */
  com.google.protobuf.ByteString
      getFormattedFactorizedBytes();
}
