// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simple.proto

package ru.spbu.pt.bd.grpc;

public interface InfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string systemName = 1;</code>
   */
  java.lang.String getSystemName();
  /**
   * <code>string systemName = 1;</code>
   */
  com.google.protobuf.ByteString
      getSystemNameBytes();

  /**
   * <code>string time = 2;</code>
   */
  java.lang.String getTime();
  /**
   * <code>string time = 2;</code>
   */
  com.google.protobuf.ByteString
      getTimeBytes();
}
