# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simple.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0csimple.proto\"\x1e\n\x0bInfoRequest\x12\x0f\n\x07printMe\x18\x01 \x01(\t\"0\n\x0cInfoResponse\x12\x12\n\nsystemName\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\t\"\x1f\n\rFactorRequest\x12\x0e\n\x06number\x18\x01 \x01(\x03\"-\n\x0e\x46\x61\x63torResponse\x12\x1b\n\x13\x66ormattedFactorized\x18\x01 \x01(\t2t\n\rSampleService\x12.\n\rgetSystemInfo\x12\x0c.InfoRequest\x1a\r.InfoResponse\"\x00\x12\x33\n\x10getFactorization\x12\x0c.InfoRequest\x1a\x0f.FactorResponse\"\x00\x42*\n\x12ru.spbu.pt.bd.grpcB\x12SampleServiceProtoP\x01\x62\x06proto3')
)




_INFOREQUEST = _descriptor.Descriptor(
  name='InfoRequest',
  full_name='InfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='printMe', full_name='InfoRequest.printMe', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=46,
)


_INFORESPONSE = _descriptor.Descriptor(
  name='InfoResponse',
  full_name='InfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='systemName', full_name='InfoResponse.systemName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='InfoResponse.time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=96,
)


_FACTORREQUEST = _descriptor.Descriptor(
  name='FactorRequest',
  full_name='FactorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='FactorRequest.number', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=129,
)


_FACTORRESPONSE = _descriptor.Descriptor(
  name='FactorResponse',
  full_name='FactorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='formattedFactorized', full_name='FactorResponse.formattedFactorized', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=176,
)

DESCRIPTOR.message_types_by_name['InfoRequest'] = _INFOREQUEST
DESCRIPTOR.message_types_by_name['InfoResponse'] = _INFORESPONSE
DESCRIPTOR.message_types_by_name['FactorRequest'] = _FACTORREQUEST
DESCRIPTOR.message_types_by_name['FactorResponse'] = _FACTORRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InfoRequest = _reflection.GeneratedProtocolMessageType('InfoRequest', (_message.Message,), dict(
  DESCRIPTOR = _INFOREQUEST,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:InfoRequest)
  ))
_sym_db.RegisterMessage(InfoRequest)

InfoResponse = _reflection.GeneratedProtocolMessageType('InfoResponse', (_message.Message,), dict(
  DESCRIPTOR = _INFORESPONSE,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:InfoResponse)
  ))
_sym_db.RegisterMessage(InfoResponse)

FactorRequest = _reflection.GeneratedProtocolMessageType('FactorRequest', (_message.Message,), dict(
  DESCRIPTOR = _FACTORREQUEST,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:FactorRequest)
  ))
_sym_db.RegisterMessage(FactorRequest)

FactorResponse = _reflection.GeneratedProtocolMessageType('FactorResponse', (_message.Message,), dict(
  DESCRIPTOR = _FACTORRESPONSE,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:FactorResponse)
  ))
_sym_db.RegisterMessage(FactorResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\022ru.spbu.pt.bd.grpcB\022SampleServiceProtoP\001'))

_SAMPLESERVICE = _descriptor.ServiceDescriptor(
  name='SampleService',
  full_name='SampleService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=178,
  serialized_end=294,
  methods=[
  _descriptor.MethodDescriptor(
    name='getSystemInfo',
    full_name='SampleService.getSystemInfo',
    index=0,
    containing_service=None,
    input_type=_INFOREQUEST,
    output_type=_INFORESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getFactorization',
    full_name='SampleService.getFactorization',
    index=1,
    containing_service=None,
    input_type=_INFOREQUEST,
    output_type=_FACTORRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SAMPLESERVICE)

DESCRIPTOR.services_by_name['SampleService'] = _SAMPLESERVICE

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class SampleServiceStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.getSystemInfo = channel.unary_unary(
          '/SampleService/getSystemInfo',
          request_serializer=InfoRequest.SerializeToString,
          response_deserializer=InfoResponse.FromString,
          )
      self.getFactorization = channel.unary_unary(
          '/SampleService/getFactorization',
          request_serializer=InfoRequest.SerializeToString,
          response_deserializer=FactorResponse.FromString,
          )


  class SampleServiceServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def getSystemInfo(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def getFactorization(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_SampleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'getSystemInfo': grpc.unary_unary_rpc_method_handler(
            servicer.getSystemInfo,
            request_deserializer=InfoRequest.FromString,
            response_serializer=InfoResponse.SerializeToString,
        ),
        'getFactorization': grpc.unary_unary_rpc_method_handler(
            servicer.getFactorization,
            request_deserializer=InfoRequest.FromString,
            response_serializer=FactorResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'SampleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaSampleServiceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def getSystemInfo(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def getFactorization(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaSampleServiceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def getSystemInfo(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    getSystemInfo.future = None
    def getFactorization(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    getFactorization.future = None


  def beta_create_SampleService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('SampleService', 'getFactorization'): InfoRequest.FromString,
      ('SampleService', 'getSystemInfo'): InfoRequest.FromString,
    }
    response_serializers = {
      ('SampleService', 'getFactorization'): FactorResponse.SerializeToString,
      ('SampleService', 'getSystemInfo'): InfoResponse.SerializeToString,
    }
    method_implementations = {
      ('SampleService', 'getFactorization'): face_utilities.unary_unary_inline(servicer.getFactorization),
      ('SampleService', 'getSystemInfo'): face_utilities.unary_unary_inline(servicer.getSystemInfo),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_SampleService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('SampleService', 'getFactorization'): InfoRequest.SerializeToString,
      ('SampleService', 'getSystemInfo'): InfoRequest.SerializeToString,
    }
    response_deserializers = {
      ('SampleService', 'getFactorization'): FactorResponse.FromString,
      ('SampleService', 'getSystemInfo'): InfoResponse.FromString,
    }
    cardinalities = {
      'getFactorization': cardinality.Cardinality.UNARY_UNARY,
      'getSystemInfo': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'SampleService', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
