// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simple.proto

package ru.spbu.pt.bd.grpc;

public interface InfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string printMe = 1;</code>
   */
  java.lang.String getPrintMe();
  /**
   * <code>string printMe = 1;</code>
   */
  com.google.protobuf.ByteString
      getPrintMeBytes();
}
